#!/bin/bash

set -e

if [[ "$1" = "purge" ]]; then
	#Automatic remove conkyrc for all users when kaisen-conky is purge
	for users in $(awk -F: '/\/home/ {printf "%s:%s\n",$1,$3}' /etc/passwd | cut -d: -f1)
	do
        	rm -f /home/$users/.conkyrc
	done

	rm -f /root/.conkyrc
fi

#DEBHELPER#
